---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrrrrrrrrr
  labels:
    app: rrrrrrrrrr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rrrrrrrrrr
  template:
    metadata:
      labels:
        app: rrrrrrrrrr
    spec:
      containers:
        - name: rrrrrrrrrr
          image: docker.io/phengbunath/rrrrrrrrrr:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
